### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 128 

### ISSUE THREAD

**Issue by AdamBebko** [yoichiro/gh-action-increment-value#5]
Hello, First off, thanks for such a great tool. We've been using it for several months now and it's really helped our workflow.

Yesterday a new error just popped up when running it:

```
Target file: build-number.json
[9](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:10)
Incremented the value from 206 to 207.
[10](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:11)
/usr/bin/git config user.name Automated Increment value
[11](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:12)
fatal: not in a git directory
[12](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:13)
✖  fatal     Error: The process '/usr/bin/git' failed with exit code 128 
[13](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:14)
    at ExecState._setResult (/node_modules/@actions/exec/lib/toolrunner.js:592:25)
[14](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:15)
    at ExecState.CheckComplete (/node_modules/@actions/exec/lib/toolrunner.js:575:18)
[15](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:16)
    at ChildProcess.<anonymous> (/node_modules/@actions/exec/lib/toolrunner.js:469:27)
[16](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:17)
    at ChildProcess.emit (node:events:527:28)
[17](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:18)
    at maybeClose (node:internal/child_process:1092:16)
[18](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:19)
    at Socket.<anonymous> (node:internal/child_process:451:11)
[19](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:20)
    at Socket.emit (node:events:527:28)
[20](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:21)
    at Pipe.<anonymous> (node:net:709:12)
[21](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:22)
✖  fatal     Failed to increment the value.
```

Here is our checkout step:

```yml
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        token: ${{ secrets.GH_TOKEN }} # must have admin permissions to repo
```

secrets.GH_TOKEN is a personal access token with all privileges checked. I regenerated it just to be sure.

Here is our step where we auto increment:

```yml
   - name: Increment build in build-number.json 
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: yoichiro/gh-action-increment-value@main
      with:
        target_file: 'build-number.json'
        prefix: 'buildNumber":'
        suffix: '}'
        commit_message: 'Increment the build number to'
    
```

Any ideas on what might be going wrong? Again, this was working perfectly for several months, and just broke yesterday (dec 19)
